### PR TITLE
Add Elixir and Io fizzbuzz solutions

### PR DESCRIPTION
**Pull request by kmoe**
As discussed in https://twitter.com/katyemoe/status/602796586758963200

### CODE REVIEW

**Comment by josephwegner** [comment]
Sorry I didn't review these today! For some reason Github isn't sending me emails. 

I will review this first thing tomorrow.

**Comment by josephwegner** [comment]
:) I don't know Io or Elixir, but these seem pretty sane. Thanks!

**Comment by josephwegner** [comment]
These are live! Thanks a bunch!

**Comment by kmoe** [comment]
Thanks - I'll make another PR when I write more fizzbuzzes!

**Pull request merged**
